### ISSUE TITLE
0.0.21版本拖拽预览过于灵敏

### ISSUE THREAD

**Issue by jump1999** [u-Sir/drag-to-preview#10]
HI，最近在测试时0.0.21时，发现从0.0.14版本开始就一直存在的问题，那就是触发机制太过于灵敏，有时候鼠标如果灵敏度较高，会很容易误触发打开新标签功能，能不能增加一个灵敏度设置，当拖拽网址超过一定阈值后才触发打开新标签。谢谢

**Comment by u-Sir** [comment]
[drag-to-preview-0.0.22-chromium-v3-test.zip](https://github.com/user-attachments/files/16318967/drag-to-preview-0.0.22-chromium-v3-test.zip)
解压后，从本地加载试下，把你认为不错的参数给一下，我也参考下 😂。

**Comment by jump1999** [comment]
挺好用的👍
