### ISSUE TITLE
chrome商店的0.0.22版本不能弹出预览窗口

### ISSUE THREAD

**Issue by Tongnier** [u-Sir/drag-to-preview#11]
- 发布在chrome商店的新版本0.0.22，在chrome商店的更新日期为2024年7月22日，**其问题是使用时不能弹出新的预览窗口，浏览器画面会直接模糊掉，但是新的预览窗口无法弹出**，我用的是edge浏览器最新版。
- edge商店的版本0.0.21没有此问题，请开发者大大看看是哪里的bug，感谢！
- 已经测试非其他拓展插件的问题。

**Comment by u-Sir** [comment]
Chrome 版本是？现在 Edge 商店也更新到 22 了，也会一样吗？
我这边测试没发现有问题 😂，可以截个设置图？

**Comment by u-Sir** [comment]
我在虚拟机上复现到了,用这个试下
[chromium-0.0.22-test.zip](https://github.com/user-attachments/files/16378798/chromium-0.0.22-test.zip)

**Comment by u-Sir** [comment]
后面这两个已知问题。Chrome 用的方法中火狐不一样，火狐的方法用在 Chrome 有也有问题，看哪个能解决先到时再用哪个了，我也有点懵了 😂

**Comment by u-Sir** [comment]
> > 后面这两个已知问题。Chrome 用的方法中火狐不一样，火狐的方法用在 Chrome 有也有问题，看哪个能解决先到时再用哪个了，我也有点懵了 😂
> 
> 好的，我先用着老版本吧，目前0.0.21没有问题

21 链接识别好像也一样有问题呀 😂

**Comment by u-Sir** [comment]
> > 21版本没有拖拽时间检测，建议只增加拖拽的阈值检测，取消掉拖拽时间检测，然后增强链接拖拽效果🌹🌹🌹
> 
> 21版本没有拖拽时间检测，建议只增加拖拽的阈值检测，取消掉拖拽时间检测，然后增强链接拖拽效果🌹🌹🌹

拖拽时间检测设置为 0 跟 21 也有区别？
