### ISSUE TITLE
A question rather than a request : drag sensitivity

### ISSUE THREAD

**Issue by aquarime** [u-Sir/drag-to-preview#14]
Hi,

Just updated _Drag to Preview_ to version 0.0.24 : no issue, nice enhancement.
I have a simple question regarding whatever version which concerns the drag sensitivity.
A user may happen to very slightly move the mouse when clicking on a link, which then calls _Drag to Preview_ when the intention  is only to open the link.

There is a dedicated Windows Registry setting which allows to modify this sensibility:
```
[HKEY_CURRENT_USER\Control Panel\Desktop]
"DragHeight"="4"
"DragWidth"="4"
```
Must  a user modify these Windows settings to increase these values applied to _Drag to Preview_ or is it possible that the extension increase this tolerance for itself?
Thanks :)

**Comment by u-Sir** [comment]
Yes, will consider adding this feature in the next version. Thank you for the suggestion!

**Comment by aquarime** [comment]
OK, thanks. Now that I better think about it, my reference to the Windows Registry was perhaps naive.

**Comment by u-Sir** [comment]
[drag_to_preview-0.0.25-firefox-test7.zip](https://github.com/user-attachments/files/16487005/drag_to_preview-0.0.25-firefox-test7.zip)
try this test version

**Comment by aquarime** [comment]
_drag_to_preview-0.0.25-firefox-test7_ installed as a temporary extension from about:debugging#/runtime/this-firefox
_Drag Settings / At least move px (do not check if 0)_ set to 16.2 : functional, as well of course as with other values :+1: 
In my experience the new Drag tolerance works perfectly. Thanks.
