### ISSUE TITLE
未来有没有可能对鼠标手势类扩展的拖曳功能做适配？

### ISSUE THREAD

**Issue by ffainy** [u-Sir/drag-to-preview#15]
比如我用的鼠标手势扩展是smartup，其中对于超链接的拖曳我是这样定义的，向右拖曳切换到新tab打开链接，向左拖曳在新tab打开链接但是不自动切换过去，向上拖曳复制链接地址，如果`drag-to-preview`能适配就能实现分配给一个具体的手势而不是随便怎么拖曳都是同一个功能🫡

**Comment by u-Sir** [comment]
会考虑，只分上下左右的话够用吗？

**Comment by ffainy** [comment]
我用的是edge，上下左右基本够用了，但是如果能加入ctrl alt shift组合键那就更棒了
另外还可以考虑一下图片类元素的拖曳👍

**Comment by u-Sir** [comment]
试下这个测试版：https://github.com/user-attachments/files/16478917/drag_to_preview-0.0.25-chromium-test5.zip

**Comment by ffainy** [comment]
拖曳方向判断和组合键都正常，挺好的，这个扩展已经能日常使用了👍
如果想更完善一点，建议可以看看smartup里关于拖曳的功能
简单来说就是区分文字/图片/超链接


![屏幕截图 2024-08-03 225607](https://github.com/user-attachments/assets/d1331256-b5c8-44fa-a564-da6bd05d3032)
![屏幕截图 2024-08-03 225550](https://github.com/user-attachments/assets/3ce17bec-59df-4803-aec6-01a447b5f784)
![屏幕截图 2024-08-03 225538](https://github.com/user-attachments/assets/39206172-93a7-402c-9946-0fb7f66ee8f3)

**Comment by u-Sir** [comment]
好的，不过感觉快要肝不动了 😂
