### ISSUE TITLE
当拖拽到标签栏时，不应打开预览窗口

### ISSUE THREAD

**Issue by 18476305640** [u-Sir/drag-to-preview#16]
![image](https://github.com/user-attachments/assets/054a4394-b481-4259-9361-056dc66160fc)
当拖拽到标签栏时，不应打开预览窗口，这样会以新标签打开，且打开了预览窗口。这肯定是不期望的。

**Comment by u-Sir** [comment]
啊。。浏览器是？插件版本是？

**Comment by 18476305640** [comment]
chrome: 127.0.6533.89
插件版本：0.0.24

**Comment by 18476305640** [comment]
> 啊。。浏览器是？插件版本是？

chrome: 127.0.6533.89
插件版本：0.0.24

**Comment by u-Sir** [comment]
方便试下这版吗：https://github.com/user-attachments/files/16479150/drag_to_preview-0.0.25-chromium-test6.zip

**Comment by 18476305640** [comment]
> 方便试下这版吗：https://github.com/user-attachments/files/16479150/drag_to_preview-0.0.25-chromium-test6.zip

我卸载使用测试了，还是一样的，你那边测试没有那个问题吗？

**Comment by 18476305640** [comment]
> 方便试下这版吗：https://github.com/user-attachments/files/16479150/drag_to_preview-0.0.25-chromium-test6.zip

我卸载原来的使用你发的使用测试了，还是一样的，你那边测试没有那个问题吗

**Comment by u-Sir** [comment]
我这边试了是没弹窗的，可以录个Gif看看操作吗 😂

**Comment by 18476305640** [comment]
> 我这边试了是没弹窗的，可以录个Gif看看操作吗 😂 我是直接拖拽链接到标签栏的

![bug](https://github.com/user-attachments/assets/7f983f32-157d-408c-996a-05dc67fd8ad6)

**Comment by 18476305640** [comment]
> 我这边试了是没弹窗的，可以录个Gif看看操作吗 😂 我是直接拖拽链接到标签栏的

我关掉所有其它插件后，发现也没这个问题，应该是被影响了

**Comment by u-Sir** [comment]
好吧，不过也顺便发现了个问题，哈哈

**Comment by 18476305640** [comment]
> 我这边试了是没弹窗的，可以录个Gif看看操作吗 😂 我是直接拖拽链接到标签栏的

你发给我的那个版本应该是修复了这个问题，在禁用掉其它插件下，用换之前（0.0.24）的那个禁用掉重启浏览器测试是存在这个问题的，而在用你发给我的那个版本（0.0.25）重启浏览器再测试是没有这个问题了，之前换你发给我的那个版本问题还存在应该是没有重启浏览器。
