### ISSUE TITLE
如果拖拽的是url，应该打开，而不要使用搜索url

### ISSUE THREAD

**Issue by 18476305640** [u-Sir/drag-to-preview#17]
![image](https://github.com/user-attachments/assets/b3f3169a-110a-461b-8af6-ebe9fb40f598)

选中普通文本进行拖拽，如果选中的内容是url应该打开，而不要使用搜索url

**Comment by u-Sir** [comment]
试下这版
https://github.com/user-attachments/files/16626647/drag_to_preview-0.0.26-chromium-test2.zip

**Comment by 18476305640** [comment]
> 试下这版 https://github.com/user-attachments/files/16626647/drag_to_preview-0.0.26-chromium-test2.zip

不行，你可以在这个[网站](https://www.cnblogs.com/zhuangjie/p/18136270)测试效果（选中链接拖动）

**Comment by u-Sir** [comment]
默认没启用的，到设置页面打开后试试

**Comment by 18476305640** [comment]
> 忘了跟你说，默认没启用的，到设置页面打开后试试

开启后，确实是可以的。
