### ISSUE TITLE
后台标签打开按钮

### ISSUE THREAD

**Issue by ydivho12123** [u-Sir/drag-to-preview#18]
现在打开窗口想后台标签页打开需要打开右键菜单才能打开，如果在预览窗口顶部放置一个后台标签页打开会更方便

**Comment by u-Sir** [comment]
[drag_to_preview-0.0.26-chromium-test3.zip](https://github.com/user-attachments/files/16645598/drag_to_preview-0.0.26-chromium-test3.zip)
这个测试版加了返回原窗口的快捷键，可以试下
