### ISSUE TITLE
Conflict with pages using the drag feature - Specific to drag-to-preview ver. 0.0.20 : FIXED

### ISSUE THREAD

**Issue by aquarime** [u-Sir/drag-to-preview#7]
I don't think this is in any way related to https://github.com/u-Sir/drag-to-preview/issues/5 but I mention it should an updated version include a fix for this issue as well.
Issue is specific to ver. 0.0.20, at least does not occur on ver. 0.0.19 (no idea about previous versions).

Pages using the drag feature to move the page's content no longer record that the mouse's left-button (the one used to drag) is released : page's content continues to be dragged even when left-button is released. Disabling _Drag to Preview_ (0.0.20) fixes the issue.

Tested on: https://www.openstreetmap.org/

For the time being, in my case, this leads to either switching back to ver. 0.0.19 either disabling ver. 0.0.20 until a fix is available.

**Comment by u-Sir** [comment]
Sorry, will check it lately.

**Comment by u-Sir** [comment]
Please check if it fixed in 0.0.21 on AMO.

**Comment by aquarime** [comment]
Just updated to 0.0.21, tested the previous drag issue at https://www.openstreetmap.org/ : FIXED :+1:
