### ISSUE TITLE
建议增加新窗口打开弹窗的快捷键

### ISSUE THREAD

**Issue by vem** [u-Sir/drag-to-preview#8]
比如拖拽打开一个窗口之后, 感觉需要长时间看这个网页, 或者需要进一步操作的话, 需要在新标签打开弹窗网页

**Comment by u-Sir** [comment]
现在只能通过右键菜单 -> 发送当前页面到原窗口，快捷键的话要到时再加了
![image](https://github.com/user-attachments/assets/43a6e7e4-59ed-4d77-a9b1-f78126e159bd)

**Comment by u-Sir** [comment]
用的Chrome，edge吗？是的话，试下这版
https://github.com/user-attachments/files/16626647/drag_to_preview-0.0.26-chromium-test2.zip

**Comment by apades** [comment]
这个功能还是很需要的，有时看久了就想保留了

**Comment by u-Sir** [comment]
> 这个功能还是很需要的，有时看久了就想保留了
  

这个不能满足吗？😂 @apades 
![image](https://github.com/user-attachments/assets/8d6b4ce9-6cc3-4b37-89a5-e8183c5cbdf3)

**Comment by apades** [comment]
才看到这个，但这个体验好怪啊，设置了就成要按住按键再拖动才弹出

**Comment by u-Sir** [comment]
> 才看到这个，但这个体验好怪啊，设置了就成要按住按键再拖动才弹出

方便单开一个 issue 来详细描述下吗？我这边没不按住也可以正常触发，这个没有设置吧？
![image](https://github.com/user-attachments/assets/b7da8e9b-c5fd-4c0c-844c-7e984e53c498)

提供下配置信息
![image](https://github.com/user-attachments/assets/0db35086-0964-4ca8-bb25-749cfb90e9d7)

**Comment by apades** [comment]
没问题了，原来是搞错设置了
